rootUrl: http://svx.aero/
gridUrl: http://127.0.0.1:4444/wd/hub

sets:
  all:
    files:
      - gemini
  board:
    files:
      - gemini/board.js
      
browsers:

  ChromeFullHD:
    windowSize: 1920x1080
    desiredCapabilities:
      browserName: chrome
      resolution: 1920x1080
      acceptSslCerts: true

  # IE:
  #   windowSize: 1920x1080
  #   desiredCapabilities:
  #     browserName: internet explorer
  #     platform: Wnidows
  #     version: 11


system:
  plugins:
    html-reporter/gemini:
      enabled: true
      path: gemini-reports
      defaultView: all

    json-reporter/gemini:
      enabled: true
      path: reports/report.json

compositeImage: true